version: '3.9'
services:
  frontend:
    build: ./frontend/delivery_app
    ports:
      - "5173:5173"
    depends_on:
      - backend
      
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PORT=3000
      - DB_USER=root
      - DB_PASSWORD=senha-mysql
      - DB_HOST=database
      - DB_NAME=delivery-app
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 60s
      retries: 5

  database:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=senha-mysql
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 30s
      retries: 5
